/** Datos de Migration_Etcbc4_v8 (007) y Etcbc4_v8a (008) extraídos 1:1 del legacy. */
export const w2sMap: Record<string, string> = {
  ">": "a", B: "b", G: "c", D: "d", H: "e", W: "f", Z: "g", X: "h", V: "i", J: "j",
  k: "k", K: "k", L: "l", m: "m", M: "m", n: "n", N: "n", S: "o", "<": "p", p: "q",
  P: "q", y: "r", Y: "r", Q: "s", R: "t", "#": "u", C: "u", F: "u", T: "v",
  "=": "", "_": " ", "[": "", "/": "",
};

export const etcbc4v8ToReplace: Record<string, (string | number)[]> = {
    "<CTRT===/": ["<CTRWT/", "עַשְׁתָּרֹות"],
    "<D>/": ["<DW>/", "עִדֹּוא"],
    "<WDD/": ["<DD/", "עֹדֵד"],
    ">CTMW</": [">CTM</", "אֶשְׁתְּמֹעַ"],
    ">DWRM/": [">DRM/", "אֲדֹרָם"],
    ">HRWN/": [">HRN/", "אַהֲרֹן"],
    ">L<L>/": [">L<LH/", "אֶלְעָלֵה"],
    ">LJ<JNJ/": [">LJ<NJ/", "אֱלִיעֵנַי"],
    ">WN==/": [">N/", "אֹן"],
    "BJT_RXB/": ["BJT_RXWB/", "בֵּית רְחֹוב"],
    "BJT_XRWN/": ["BJT_XWRWN/", "בֵּית חֹורֹון"],
    "BLC>YR/": ["BL>CYR/", "בֵּלְאשַׁצַּר"],
    "BNJMJN/": ["BNJMN/", "בִּנְיָמִן"],
    "CJLW/": ["CLW=/", "שִׁלֹו"],
    "CPM==/": ["CPJM/", "שֻׁפִּים"],
    "DJBWN/": ["DJBN/", "דִּיבֹן"],
    "DW>G/": ["D>G/", "דֹּאֵג"],
    "DWDWHW/": ["DDWHW/", "דֹּדָוָהוּ"],
    "FJ>WN/": ["FJ>N/", "שִׂיאֹן"],
    "FRJWN/": ["FRJN/", "שִׂרְיֹן"],
    "FWRQ/": ["FRQ==/", "שֹׂרֵק"],
    "HRM=/": ["HRWM/", "הָרוּם"],
    "J<ZJR/": ["J<ZR/", "יַעְזֵר"],
    "JBC=/": ["JBJC=/", "יָבֵישׁ"],
    "JBC==/": ["JBJC==/", "יָבֵישׁ"],
    "JCJMWN=/": ["JCJMN/", "יְשִׁימֹן"],
    "JHWCW</": ["JHWC</", "יְהֹושֻׁעַ"],
    "JHWD/": ["JHD/", "יְהוּד"],
    "JPW>/": ["JPW/", "יָפֹו"],
    "JTJR/": ["JTR===/", "יַתִּר"],
    "KJLPWT/": ["KJLP/", "כֵּילָף"],
    "KPRJM=/": ["KPJRJM=/", "כְּפִירִים"],
    "KSLWT/": ["KSWLT/", "כְּסוּלֹת"],
    "MJMJN/": ["MJMN/", "מִיָּמִן"],
    "MR>CH/": ["MRCH=/", "מָרֵשָׁה"],
    "PRZWT/": ["PRZH/", "פְּרָזָה"],
    "PYLWT/": ["PYLH/", "פְּצָלָה"],
    "QDRNJT/": ["QDRNJT", "קְדֹרַנִּית"],
    "QR>=/": ["QWR>/", "קֹורֵא"],
    "QWH/": ["QW>/", "קְוֵא"],
    "R>MWT=/": ["RMT=/", "רָמֹת"],
    "TGRMH/": ["TWGRMH/", "תֹּוגַרְמָה"],
    "TPWX==/": ["TPX/", "תַּפֻּחַ"],
    "XKMNJ/": ["XKMWNJ/", "חַכְמֹונִי"],
    "XLWN=/": ["XLN=/", "חֹלֹן"],
    "XNTWN/": ["XNTN/", "חַנָּתֹן"],
    "XRXR=/": ["XRXWR/", "חַרְחוּר"],
    "YWPR/": ["YPR/", "צֹפַר"],
    "YXYXWT/": ["YXYXH/", "צַחְצָחָה"],
    "ZBWLWN/": ["ZBWLN/", "זְבוּלֻן"],
    "KRKRWT/": ["KRKRH/", "כִּרְכָּרָה", "she-camels", "she-camel", "Kamelstuten", "Kamelstute"],
    "MBDLWT/": ["MBDLH/", "מִבְדָּלָה", "separate places, enclaves", "separate place, enclave", "Enklaven", "Enklave"],
    "ZJQWT/": ["ZJQH/", "זִיקָה", "fire-arrows", "fire-arrow", "Brandpfeile", "Brandpfeil"],
    "ZQJM=/": ["ZQ/", "זֵק", "fire-arrows", "fire-arrow", "Brandpfeile", "Brandpfeil"],
};

export const etcbc4v8ToRemove: string[] = [
    "BJT_XRWN_<LJWN/",
    "BJT_XRWN_TXTWN/",
    "DJBWN_GD/",
    "GRN_>VD/",
    "XYJ_HMNXWT/",
    "CR=/",
    "KLNH=/",
    "MN===/",
];

export const etcbc4v8ToAdd: (string | number)[][] = [
    ["WCNJ/", "NA", "וַשְׁנִי", 1, "Chronica_I", 6, 13, "Vashni", "Waschni"],
    [">BJCJ/", "NA", "אֲבִישַׁי", 19, "Samuel_I", 26, 6, "Abishai", "Abischai"],
    ["PRT=/", "NA", "פֹּרָת", 2, "Genesis", 49, 22, "tamarisk?", "Tamariske?"],
    ["TNJM/", "NA", "תַּנִּים", 2, "Ezechiel", 29, 3, "sea-monster", "Seeungeheuer"],
    ["XJL==[", "qal", "חיל", 5, "Genesis", 8, 10, "wait", "warten"],
    ["XJL==[", "hit", "חיל", 5, "Psalmi", 37, 7, "wait", "warten"],
    ["XJL==[", "piel", "חיל", 5, "Iob", 35, 14, "wait", "warten"],
];

export const etcbc4v8ToCopy: (string | number)[][] = [
    ["G<C[", "hit", "Samuel_II", 22, 8, "htpo", "Jeremia", 25, 16],
    ["CRC[", "piel", "Psalmi", 52, 7, "poel", "Jesaia", 40, 24],
    ["JD<[", "pual", "Reges_II", 10, 11, "poal", "Samuel_I", 21, 3],
    ["S<R[", "piel", "Sacharia", 7, 14, "poel", "Hosea", 13, 3],
];

export const etcbc4v8Stems: string[][] = [
    ["CFH[", "piel", "poel"],
    ["CPV[", "piel", "poel"],
    ["CRC[", "pual", "poal"],
    ["N>Y[", "hit ", "htpo"],
    ["ZRM[", "piel", "poel"],
];

export const wordFeatMap: Record<string, string> = {
  text: "g_word",
  text_nopunct_translit: "g_word_nopunct_translit",
  text_translit: "g_word_translit",
  text_utf8: "g_word_utf8",
  text_cons_utf8: "g_word_cons_utf8",
  text_nocant_utf8: "g_word_nocant_utf8",
  vocalized_lexeme: "g_voc_lex",
  vocalized_lexeme_cons_utf8: "g_voc_lex_cons_utf8",
  vocalized_lexeme_translit: "g_voc_lex_translit",
  vocalized_lexeme_utf8: "g_voc_lex_utf8",
  g_qere: "qere",
  g_qere_translit: "qere_translit",
  g_qere_utf8: "qere_utf8",
};
